name: Build application executables

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python 3.10
              id: cp310
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10'
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller opencv-python-headless opencv-contrib-python
                  pip install -r requirements.txt
            - name: Make
              run: make
            - name: Install libgl1
              if: matrix.os == 'ubuntu-latest'
              run: sudo apt-get install libgl1 libegl1
            - name: Run PyInstaller (windows)
              if: matrix.os == 'windows-latest'
              run: pyinstaller -n "OnAirScreen" -F --noconsole -i "images/oas_icon.ico" start.py
            - name: Run PyInstaller (ubuntu)
              if: matrix.os == 'ubuntu-latest'
              run: pyinstaller -n "OnAirScreen" -F --noconsole start.py
            - uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.os }}
                  path: dist/*
